apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - mastodo-main-mky5d
  containers:
  - name: ubuntu
    image: ubuntu
    command:
      - "sleep"
      - "604800"
